### ISSUE TITLE
Segmentation fault whenever I run statusbar

### ISSUE THREAD

**Issue by MuriloOJr** [snobb/dwm-statusbar#5]
Whenever I run statusbar it suffers a segmentation fault and ends abruptely. Everything is using the default configuration except the wireless interface name (set to wlp1s0), the compiler (set to cc) and the installation path (set to /usr/bin).

the "build_host.h" file generates the following:
`
#define BUILD_HOST "arch"
#define BUILD_OS "Linux"
#define BUILD_PLATFORM "x86_64"
#define BUILD_KERNEL "4.15.15-1-ARCH"
#define BUILD_VERSION "37.a855ee7"
#define BAT_NOW "/charge_now"
#define BAT_FULL "/charge_full"
#define BAT_STAT "/status"
#define LNK_PATH "/sys/class/net/wlp1s0/operstate"
`

**Comment by snobb** [comment]
The BAT_NOW, BAT_FULL and BAT_STAT look wrong. Are you on a laptop (with a battery)? Otherwise there must have been a change in the linux kernel and you may need to adjust the line, setting the BATPATH variable in the Makefile. It works fine on a stable Debian.

**Comment by MuriloOJr** [comment]
Yes, I'm on a laptop without a battery. If that's the case, should I remove the `percent_bar` function call from main?
