### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by richardschembri** [snobb/dwm-statusbar#6]
Can you kindly add a license to the repository?

**Comment by snobb** [comment]
Done, thanks.

**Comment by richardschembri** [comment]
Thank you!

**Comment by snobb** [comment]
Thanks for reporting! For status bars have a look at slstatus and other projects on suckless.org: http://dwm.suckless.org/status_monitor/

**Comment by richardschembri** [comment]
I was already aware but thanks for the heads up.
